import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { Leaf } from "lucide-react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-[#e0f4e8]">
          <header className="px-4 lg:px-6 h-16 flex items-center">
            <Link className="flex items-center justify-center mt-8" href="/">
              <Image src="/images/boba.png"
                alt="food logo"
                className="mx-auto"
                width={120}
                height={120} />
              <div className="ml-2 text-xl font-semibold text-teal-800">MealTracker</div>
            </Link>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
