import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { cookies } from "next/headers";
import LogoutButton from "@/components/logoutButton";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allCookies = cookies();
  const sessionCookie = allCookies.get("JSESSIONID");


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-[#e0f4e8]">
          <header className="px-4 lg:px-6 h-24 flex items-center justify-between">
            <Link className="flex items-center justify-center" href="/">
              <Image
                src="/images/boba.png"
                alt="food logo"
                className="mx-auto"
                width={120}
                height={120}
              />
              <div className="ml-2 text-xl font-semibold text-teal-800">
                MealTracker
              </div>
            </Link>
            {sessionCookie && <LogoutButton />}
          </header>
          <main className="content">{children}</main>
        </div>
      </body>
    </html>
  );
}
